---
title: "Lab 6"
output: html_document
date: "2023-06-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
heart_disease <- read_csv("http://www.stat.cmu.edu/cmsac/sure/2022/materials/data/health/intro_r/heart_disease.csv")
(heart_disease)
```

```{r}
heart_disease %>%
  ggplot(aes(x = Cost, y = Gender,
             color = Drugs)) +
  geom_point(alpha = 0.5) +
  labs(x = "Cost", y = "Gender",
       color = "Number of drugs") +
  theme_bw()
```

```{r}
# Import necessary packages
library(ggplot2)

# Create a histogram
ggplot(heart_disease, aes(x = Cost)) +
  geom_histogram(bins = 50, fill="blue", color="black", alpha=0.7) +
  labs(x="Cost", y="Frequency", title="Histogram of Costs") +
  theme_minimal()
```

```{r}
heart_disease <- heart_disease %>%
  mutate(log_cost = log(Cost + 1))
```

```{r}
# Import necessary packages
library(ggplot2)

# Create a histogram
ggplot(heart_disease, aes(x = log_cost)) +
  geom_histogram(bins = 30, fill="black", color="black", alpha=0.7) +
  labs(x = "Cost", y = "Frequency", title = "Histogram of Cost") +
  theme_minimal()
```

```{r}
heart_disease %>%
  mutate(model_preds = predict(log_cost_lm)) %>%
  ggplot(aes(x = model_preds, y = log_cost)) +
  geom_point(alpha = 0.75) +
  geom_abline(slope = 1, intercept = 0,
              linetype = "dashed", color = "red") +
  theme_bw() +
  labs(x = "Predictions", y = "Observed log(Cost + 1)")
```

```{r}
multi_cost_lm <- lm(log_cost ~ Cost + Gender, 
                   data = heart_disease)
```

```{r}
gender_cost_lm <- lm(log_cost ~ Gender, data = heart_disease)
```

```{r}
heart_disease %>%
  mutate(model_preds = predict(gender_cost_lm)) %>%
  ggplot(aes(x = log_cost, y = model_preds)) +
  geom_point(alpha = 2) +
  facet_wrap(~ Gender, ncol = ) +
  theme_bw() +
  labs(x = "Actual log(Cost + 1)", 
       y = "Predicted log(Cost + 1)")
```